name: Deploy to Production Server

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for deployment"
        required: false
        default: "Manual deployment"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Use the 'production' environment
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create target directory on Production Server
        env:
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
          APP_PATH: ${{ vars.DEPLOY_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "mkdir -p $APP_PATH"

      - name: Copy deployment files to Production Server
        env:
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
          APP_PATH: ${{ vars.DEPLOY_PATH }}
        run: |
          scp -o StrictHostKeyChecking=no -r \
            ci-logs.sh \
            ci-pull.sh \
            ci-start.sh \
            ci-stop.sh \
            Dockerfile \
            docker-compose.yml \
            docker-compose.staging.yml \
            docker-compose.production.yml \
            $DEPLOY_USER@$DEPLOY_HOST:$APP_PATH/

      - name: Deploy to Production Server
        env:
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
          DEPLOY_USER: ${{ vars.DEPLOY_USER }}
          APP_PATH: ${{ vars.DEPLOY_PATH }}
        run: |
          echo "Deploying to Production Server at $APP_PATH.."
          echo "Reason for deployment: ${{ github.event.inputs.reason }}"
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << EOF
            cd $APP_PATH
            ./ci-pull.sh
            ./ci-stop.sh production
            ./ci-start.sh production standalone
          EOF
