name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for deployment"
        required: false
        default: "Manual deployment"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read # Only read is needed, as CI pushes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}

      - name: Deploy to Production Server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST_PRODUCTION }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER_PRODUCTION }}
        run: |
          echo "Reason for deployment: ${{ github.event.inputs.reason }}"
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            cd /path/to/your/app # IMPORTANT: Replace with the actual path to your application on the server
            ./ci-pull.sh
            ./ci-start.sh production swarm
          EOF
